##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pluniwcv/freeware.fyi/
    - /bin/cp -r /home/pluniwcv/repositories/freeware-dot-fyi/* $DEPLOYPATH
